# SwiftLint configuration for MemoryReel iOS and TV apps
# Version: 0.50.3

# Paths to include for linting
included:
  - src/ios/MemoryReel
  - src/ios/MemoryReelTV

# Paths to exclude from linting
excluded:
  - src/ios/Pods
  - src/ios/vendor
  - src/ios/fastlane
  - src/ios/scripts

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces

# Opt-in rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Analyzer rules
analyzer_rules:
  - unused_declaration
  - unused_import

# Custom rules
custom_rules:
  api_availability_prefix:
    name: "API Availability Prefix"
    regex: '@available[\s]*\([\s]*iOS[\s]*([0-9]{1,2})[\s]*\.[\s]*([0-9]{1,2})'
    message: "Availability annotation should specify minimum deployment target"
    severity: warning
  logger_force_unwrap:
    name: "Logger Force Unwrap"
    regex: 'Logger\.shared\..*\!'
    message: "Avoid force unwrapping in logging calls"
    severity: warning

# Line length
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

# Function body length
function_body_length:
  warning: 50
  error: 100

# Type body length
type_body_length:
  warning: 300
  error: 500

# File length
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 15
  error: 25

# Type name
type_name:
  min_length: 3
  max_length: 50

# Identifier name
identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - URL
    - x
    - y

# Nesting
nesting:
  type_level:
    warning: 2
    error: 3

# Large tuple
large_tuple:
  warning: 3
  error: 4