# Kubernetes API version: v1
# Purpose: Base namespace configuration for MemoryReel platform
# Components: Resource quotas, limit ranges, and network policies
apiVersion: v1
kind: Namespace
metadata:
  name: memoryreel
  labels:
    app: memoryreel
    managed-by: kustomize
    environment: base
    component: platform
    security-tier: restricted
    backup-policy: required
  annotations:
    description: "Base namespace for MemoryReel platform services"
    environment: "base"
    kubernetes.io/metadata.name: "memoryreel"
    monitoring.memoryreel.com/enabled: "true"
    backup.memoryreel.com/retention: "30d"
    security.memoryreel.com/compliance: "soc2,gdpr"
    network.memoryreel.com/policy: "restricted"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: memoryreel-quota
  namespace: memoryreel
spec:
  hard:
    # Compute resources
    requests.cpu: "16"
    requests.memory: "32Gi"
    limits.cpu: "32"
    limits.memory: "64Gi"
    # Storage resources
    requests.storage: "1000Gi"
    persistentvolumeclaims: "50"
    # Object count limits
    pods: "100"
    services: "30"
    configmaps: "50"
    secrets: "50"
    replicationcontrollers: "30"
    deployments.apps: "30"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: memoryreel-limits
  namespace: memoryreel
spec:
  limits:
  - type: Container
    default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "200m"
      memory: "256Mi"
    min:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "4"
      memory: "8Gi"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: memoryreel
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace
  namespace: memoryreel
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: memoryreel
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-monitoring
  namespace: memoryreel
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
    ports:
    - port: 9090
      protocol: TCP
    - port: 9091
      protocol: TCP
    - port: 9092
      protocol: TCP
    - port: 9093
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-controller
  namespace: memoryreel
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    ports:
    - port: 80
      protocol: TCP
    - port: 443
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: memoryreel
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP